### ISSUE TITLE
Ansible: update apt-get install commands to new syntax

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#255]
The old way of doing apt with-items is deprecated.  The new way is to declare a variable for all the package names.

## New style for apt-get install
```YAML
- name: "Install Dependencies"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "postgis"
```

## Old, deprecated style
```YAML
- name: "Install Dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgis"
```
